[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
shaker = "6jHCAwbMrxP8RoRyvRnEMuHDXi2gBM6RuUWvygRSEeok"

[programs.localnet]
shaker = "6jHCAwbMrxP8RoRyvRnEMuHDXi2gBM6RuUWvygRSEeok"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/vesper3023/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
